### ISSUE TITLE
Availability dates for multi day

### ISSUE THREAD

**Issue by zbarahal** [zbarahal/VEST#35]
This block of code in forms.py has some very weird behavior. You have to undo the comment in the most recent commit to get it this way. If you look at the value of the matrix in the for loop, the dates are correct, but at the end of the while loop, all the dates will be the later date. Somehow the matrix is being modified. I am using this avail matrix to store the avail time/dates and just passing indices from the front end to the back end and then using those indices to retrieve data from the matrix. This behavior works for single day events but gets the dates wrong for multi days

row_time = self.event.start_time
		j = 0
		while True :
			for i in range(0,self.day_diff):
				self.avail_matrix[i][j] = row_time + timedelta(days=i)
			j += 1
			#roll back the time by a day if it goes over the midnight mark since we are already incrementing the days
			row_time += timedelta(minutes=30)
			if (row_time.strftime('%H:%M') == '00:00'):
					row_time -= timedelta(days=1)
			if self.time_diff == 24:
				if j>=48:
					break
			else:
				row_hours = int(row_time.strftime('%H'))
				end_hours = int(self.event.end_time.strftime('%H')) 
				row_minutes = int(row_time.strftime('%M'))
				end_minutes = int(self.event.end_time.strftime('%M'))
				if row_hours >= end_hours :
					if row_minutes == end_minutes :
						break

**Comment by tsyoshimoto** [comment]
Now it should work. It shouldn't give the same date anymore.
