### ISSUE TITLE
Redo login/splash page

### ISSUE THREAD

**Issue by zbarahal** [zbarahal/VEST#41]
Login page is not consistent with rest of site. A splash page like you mentioned in class would be great.

**Comment by chuxtina** [comment]
8b0fb9a3a3e331bcc59786afbac2b399f06a230e

**Comment by chuxtina** [comment]
Made changes to login 9dcb5d4aa8d9a0ee1cae676db474b05a9be90429

**Comment by chuxtina** [comment]
i think after logo is finished we can make more changes..
